openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags:
  - name: Guest
  - name: Admin
paths:
  /api/admin/bookings:
    get:
      operationId: AdminApi_getUpcomingBookings
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
      tags:
        - Admin
  /api/admin/event-types:
    post:
      operationId: AdminApi_createEventType
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventType'
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                description:
                  type: string
                durationMinutes:
                  type: integer
                  format: int32
              required:
                - id
                - name
                - description
                - durationMinutes
  /api/admin/slots:
    get:
      operationId: AdminApi_getSlots
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminSlot'
      tags:
        - Admin
    post:
      operationId: AdminApi_createSlots
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminSlot'
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AdminSlot'
  /api/bookings:
    post:
      operationId: GuestApi_createBooking
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Guest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventTypeId:
                  type: string
                slotTime:
                  type: string
                guestName:
                  type: string
                guestEmail:
                  type: string
              required:
                - eventTypeId
                - slotTime
                - guestName
                - guestEmail
  /api/event-types:
    get:
      operationId: GuestApi_getEventTypes
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventType'
      tags:
        - Guest
  /api/event-types/{eventTypeId}/slots:
    get:
      operationId: GuestApi_getSlots
      parameters:
        - name: eventTypeId
          in: path
          required: true
          schema:
            type: string
        - name: from
          in: query
          required: true
          schema:
            type: string
          explode: false
        - name: to
          in: query
          required: true
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Slot'
      tags:
        - Guest
components:
  schemas:
    AdminSlot:
      type: object
      required:
        - dayOfWeek
        - startTime
        - endTime
      properties:
        dayOfWeek:
          type: integer
          format: int32
        startTime:
          type: string
        endTime:
          type: string
    Booking:
      type: object
      required:
        - id
        - eventTypeId
        - slotTime
        - guestName
        - guestEmail
        - createdAt
      properties:
        id:
          type: string
        eventTypeId:
          type: string
        slotTime:
          type: string
        guestName:
          type: string
        guestEmail:
          type: string
        createdAt:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    EventType:
      type: object
      required:
        - id
        - name
        - description
        - durationMinutes
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        durationMinutes:
          type: integer
          format: int32
    Owner:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    Slot:
      type: object
      required:
        - startTime
        - eventTypeId
        - status
      properties:
        startTime:
          type: string
        eventTypeId:
          type: string
        status:
          $ref: '#/components/schemas/SlotStatus'
    SlotStatus:
      type: string
      enum:
        - available
        - booked